{
 "title": "Space Weather Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Estimated Planetary K Index",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Kp Index",
     "fill": "null",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" }
     ],
     "measurement": "exec_kindex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NOAA Scales Geomagnetic Storms Legend",
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 10, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <style>\n        .legend {\n            display: flex;\n            width: 100%;\n            text-align: center;\n            font-family: Arial, sans-serif;\n        }\n        .legend div {\n            flex: 1; /* Equal width for each section */\n            color: white;\n            padding: 0px;\n            font-size: 12px;\n        }\n        .green { background-color: #4CAF50; } /* Kp < 5 */\n        .yellow { background-color: #FFEB3B; color: black; } /* Kp = 5 (G1) */\n        .orange { background-color: #FF9800; } /* Kp = 6 (G2) */\n        .darkorange { background-color: #FF5722; } /* Kp = 7 (G3) */\n        .red { background-color: #F44336; } /* Kp = 8, 9- (G4) */\n        .darkred { background-color: #B71C1C; } /* Kp = 9o (G5) */\n    </style>\n</head>\n<body>\n    <div class=\"legend\">\n        <div class=\"green\">Kp < 5</div>\n        <div class=\"yellow\">Kp = 5 (G1)</div>\n        <div class=\"orange\">Kp = 6 (G2)</div>\n        <div class=\"darkorange\">Kp = 7 (G3)</div>\n        <div class=\"red\">Kp = 8, 9- (G4)</div>\n        <div class=\"darkred\">Kp = 9o (G5)</div>\n    </div>\n</body>\n</html>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "NOAA 3-Day Forecast",
   "type": "logs",
   "gridPos": { "h": 28, "w": 9, "x": 10, "y": 2 },
   "targets": [
    {
     "measurement": "noaa_forecast",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GOES Proton Flux and Electron Flux",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "measurement": "exec_protonflux",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "exec_electonflux",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tonight's Aurora Viewline Forecast",
   "type": "text",
   "gridPos": { "h": 11, "w": 4, "x": 6, "y": 4 },
   "options": {
    "content": "<img src='https://services.swpc.noaa.gov/experimental/images/aurora_dashboard/tonights_static_viewline_forecast.png' alt='WSA-Enlil Solar Wind Prediction' width='100%' height='100%'/>"
   }
  },
  {
   "title": "WSA-Enlil Prediction",
   "type": "text",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 15 },
   "options": {
    "content": "<div id=\"animationContainer\">\n  <img id=\"animationFrame\" src=\"\" alt=\"WSA-Enlil Animation Frame\">\n</div>\n\n<script>\n  const baseUrl = \"https://services.swpc.noaa.gov\";\n  const jsonUrl = \"https://services.swpc.noaa.gov/products/animations/enlil.json\";\n  let images = [];\n  let currentIndex = 0;\n\n  function preloadImages(urls) {\n    const loadedImages = [];\n    urls.forEach(url => {\n      const img = new Image();\n      img.src = url;\n      img.onload = () => {\n        loadedImages.push(img);\n        if (loadedImages.length === urls.length) {\n          images = loadedImages; // Assign fully loaded images to the global array\n          changeImage(); // Start animation after all images are loaded\n        }\n      };\n    });\n  }\n\n  function changeImage() {\n    if (images.length > 0) {\n      document.getElementById('animationFrame').src = images[currentIndex].src;\n      document.getElementById('animationFrame').alt = \"WSA-Enlil Image for \" + images[currentIndex].src.split('/').pop();\n      currentIndex = (currentIndex + 1) % images.length;\n      setTimeout(changeImage, 100); // Change image every second\n    }\n  }\n\n  fetch(jsonUrl)\n    .then(response => response.json())\n    .then(data => {\n      const imageUrls = data.map(item => baseUrl + item.url);\n      preloadImages(imageUrls);\n    })\n    .catch(error => console.error('Error fetching images:', error));\n</script>\n\n<style>\n  #animationContainer {\n    width: 100%;\n    height: auto;\n    text-align: center;\n  }\n  #animationFrame {\n    width: 100%;\n    height: auto;\n  }\n</style>\n"
   }
  }
 ]
}